// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // PKCE: OAuth2 Authorization Code com Proof Key for Code Exchange — padrao
    // recomendado para SPAs. Substitui o implicit flow (deprecated em OAuth2.1):
    // o code_verifier nunca trafega na URL, eliminando vetor de interceptacao do
    // access_token via referer/log/historico de browser.
    flowType: "pkce",
    // Processa fragmento/query do callback OAuth (#access_token=..., ?code=...)
    // automaticamente ao montar o cliente. Sem isso, voltar do Google na pagina
    // de callback nao popula sessao — usuario fica autenticado no Auth provider
    // mas o cliente JS nao sabe.
    detectSessionInUrl: true,
  },
});
